### ISSUE TITLE
Sanity check ruins docker build

### ISSUE THREAD

**Issue by jnylen** [olegantonyan/translateable#6]
Hi @olegantonyan,
I have an issue where translateable's sanity check ruins a docker build because it demands a connection to Postgresql.

```
/honeybee/vendor/bundle/ruby/2.3.0/bundler/gems/translateable-b1fe06d02ebd/lib/translateable.rb:23:in `translateable_sanity_check'
/honeybee/vendor/bundle/ruby/2.3.0/bundler/gems/translateable-b1fe06d02ebd/lib/translateable.rb:15:in `block in translateable'
/honeybee/vendor/bundle/ruby/2.3.0/bundler/gems/translateable-b1fe06d02ebd/lib/translateable.rb:14:in `each'
/honeybee/vendor/bundle/ruby/2.3.0/bundler/gems/translateable-b1fe06d02ebd/lib/translateable.rb:14:in `translateable'
/honeybee/app/models/actor.rb:53:in `<class:Actor>'
/honeybee/app/models/actor.rb:42:in `<top (required)>
```

**Edit:** Yup. I commented the sanity check and it passed through correctly. You can't even db:migrate using docker with it not commented as the tables doesn't exist yet.

**Comment by olegantonyan** [comment]
Hi
Well, those sanity checks are called when `transateable` method gets called, i.e. on model class load. At this point the db connection has to be established. I'm not sure how this nay cause problems with docker. What exactly are you trying to do?

**Comment by jnylen** [comment]
I try to load schema into the test CI database. 
Which then tells me the table doesn't exist. 

Might be some issue on preload.

**Comment by olegantonyan** [comment]
You mean db:schema:load ?

**Comment by jnylen** [comment]
@olegantonyan,
Let try do explain it a bit better:

Try to load schema via db:schema:load or by migrations fails on both.
Due to:
1. Table has not been created yet so they can't test if the column doesn't exist (aka it runs sanity check before the schema is there) - Gitlab CI
2. Building a docker build fails due to Postgres is not running (I have a seperate HA that isn't running on the same machine it's built on) but the database tests has already been run on Gitlab CI

**Comment by olegantonyan** [comment]
Ok. So, we can fix 2 by checking if there is a database connection before running sanity check and skip if there is not. But for 1 I'm not sure what is the best way to handle such situation. Do you have ideas?

**Comment by jnylen** [comment]
Hi @olegantonyan,
Regarding 1, maybe do test if there is a database connection then check if table exists or not. Skip on both?

**Comment by olegantonyan** [comment]
Ok, I've added this check to version 0.1.5. It should help

**Comment by jnylen** [comment]
I'll try to check this tomorrow or today.

**Comment by jnylen** [comment]
Hi @olegantonyan,
Still issues where the sanity check is run before the table even exists on migration:
```
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "actors" does not exist
LINE 5:                WHERE a.attrelid = '"actors"'::regclass

/builds/honeybee/honeybee.it/vendor/ruby/2.3.0/gems/translateable-0.1.5/lib/translateable.rb:24:in `translateable_sanity_check'
/builds/honeybee/honeybee.it/vendor/ruby/2.3.0/gems/translateable-0.1.5/lib/translateable.rb:15:in `block in translateable'
/builds/honeybee/honeybee.it/vendor/ruby/2.3.0/gems/translateable-0.1.5/lib/translateable.rb:14:in `each'
/builds/honeybee/honeybee.it/vendor/ruby/2.3.0/gems/translateable-0.1.5/lib/translateable.rb:14:in `translateable'
```

**Comment by olegantonyan** [comment]
What if we add environment variable to disable those checks?

**Comment by olegantonyan** [comment]
I've added `DISABLE_TRANSLATEABLE_SANITY_CHECK` environment variable. Set it to something (true, for example) to disable those checks completely

**Comment by jnylen** [comment]
Hi @olegantonyan,
I finally got around and fixing most things on my website. Using DISABLE_TRANSLATEABLE_SANITY_CHECK=1 does indeed help.

So i'm closing this.
